In [1]:
import pandas as pd
import numpy as np
import math
import operator
from scipy.stats import norm
import pandas as pd

In [2]:
column=['sepal_length','sepal_width','petal_length','petal_width','type']
iris=pd.read_csv("iris (1).data",names=column)

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width         type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
print(iris['type'].value_counts())

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: type, dtype: int64


In [5]:
print(iris.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [6]:
#Normalising the data set


Data = iris.drop("type", axis='columns')
D=['sepal_length','sepal_width','petal_length','petal_width']
values = Data.apply(lambda x: (x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0)))
values.head()

sepal_length  sepal_width  petal_length  petal_width
0      0.222222     0.625000      0.067797     0.041667
1      0.166667     0.416667      0.067797     0.041667
2      0.111111     0.500000      0.050847     0.041667
3      0.083333     0.458333      0.084746     0.041667
4      0.194444     0.666667      0.067797     0.041667

In [7]:
#Function for calculation of Euclidian distance

def euclidianDistance(data1, data2, length):
    distance = 0
    for x in range(length):
        distance += np.square(data1[x] - data2[x])
    return np.sqrt(distance)

In [8]:
# calculation of 5 nearest neighbors and the class to which test set belongs to.

def knn(trainingSet, test_data, k):
 
    distances = {}
    sort = {}
    length = test_data.shape[1]

    
#Calculating euclidean distance between each row of training data and test data
    for x in range(len(trainingSet)):
        
       
        dist = euclidianDistance(test_data, trainingSet.iloc[x], length)
        distances[x] = dist[0]
       
         
    
# Sorting them on the basis of distance
    sorted_d = sorted(distances.items(), key=operator.itemgetter(1)) #by using it we store indices also
    sorted_d1 = sorted(distances.items())
    print(sorted_d[:5])
    print(sorted_d1[:5])
    neighbors = []
    
    
# Extracting 5 nearest neighbors
    for x in range(k):
        neighbors.append(sorted_d[x][0])
        counts = {"Iris-setosa":0,"Iris-versicolor":0,"Iris-virginica":0}
    
    
# Calculating the class it belongs to
    for x in range(len(neighbors)):
        response = trainingSet.iloc[neighbors[x]][-1]
 
        if response in counts:
            counts[response] += 1
        else:
            counts[response] = 1
            
    sorting = sorted(counts.items(), key=operator.itemgetter(1), reverse=True)
    return(sorting[0][0],neighbors)

In [9]:
#giving input 1st test data & Checking its class


testSet = [[5.1, 2.5, 3.2, 4.3]]
test = pd.DataFrame(testSet)
result,neigh = knn(iris, test, 5) # 3 inputs, first the dataset, second a test record and third the number of neighbours


print('********************************************')
print("the neighbors are:",neigh)
print("the flower is:",result)

[(114, 2.792848008753788), (106, 2.9137604568666924), (121, 2.9189039038652846), (113, 2.9816103031751147), (59, 2.9916550603303182)]
[(0, 4.588027898781785), (1, 4.509988913511872), (2, 4.5902069670114), (3, 4.5066617356975), (4, 4.611941023040083)]
********************************************
the neighbors are: [114, 106, 121, 113, 59]
the flower is: Iris-virginica


In [10]:
#giving input 2nd test data & Checking its class


testSet = [[4.9, 3, 1.4, 0.2]]
test = pd.DataFrame(testSet)
result,neigh = knn(iris, test, 5) # 3 inputs, first the dataset, second a test record and third the number of neighbours


print('**********************************************')
print("the neighbors are:",neigh)
print("the flower is:",result)

[(1, 0.0), (45, 0.14142135623730986), (12, 0.1414213562373099), (9, 0.17320508075688784), (34, 0.17320508075688784)]
[(0, 0.5385164807134502), (1, 0.0), (2, 0.30000000000000016), (3, 0.3316624790355407), (4, 0.608276253029822)]
**********************************************
the neighbors are: [1, 45, 12, 9, 34]
the flower is: Iris-setosa


In [11]:
#giving input 3rd test data & Checking its class


testSet = [[6, 3, 4.8, 1.8]]
test = pd.DataFrame(testSet)
result,neigh = knn(iris, test, 5) # 3 inputs, first the dataset, second a test record and third the number of neighbours


print('***********************************************')
print("the neighbors are:",neigh)
print("the flower is:",result)

[(138, 0.0), (127, 0.14142135623730964), (70, 0.22360679774997896), (126, 0.2828427124746193), (149, 0.31622776601683766)]
[(0, 3.8961519477556315), (1, 3.9153543900903784), (2, 4.066939881532551), (3, 3.9268307832143723), (4, 3.9344631145812)]
***********************************************
the neighbors are: [138, 127, 70, 126, 149]
the flower is: Iris-virginica


In [12]:
#Accuracy Prediction

X = iris.iloc[:, :-1].values
y = iris.iloc[:, -1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0) #taking 25% test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier

In [13]:
#Giving K=5 and calculating accuracy

classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
Ac=accuracy_score(y_test, y_pred)
print("The accuracy is------>",Ac*100,"%")

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
The accuracy is------> 97.36842105263158 %


In [14]:
#Giving K=6 and calculating accuracy

classifier = KNeighborsClassifier(n_neighbors = 6, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
Ac=accuracy_score(y_test, y_pred)
print("The accuracy is------>",Ac*100,"%")

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
The accuracy is------> 97.36842105263158 %


In [15]:
#Giving K=7 and calculating accuracy

classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
Ac=accuracy_score(y_test, y_pred)
print("The accuracy is------>",Ac*100,"%")



[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
The accuracy is------> 97.36842105263158 %


In [16]:
#Here we can see, even in increasing the numbers of K, the percentage accuracy is same,
#but as we decrease the value of K , the pecentage accuracy will decrease.