In [1]:
#importing the libaries
import numpy as np
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
import operator

#function for measurement of eculidian distance
def ecu_distance(x1,x_train):
    distance={}
    counter=1
    for i in x_train:
        distance[counter]=np.sqrt(np.sum((x1 - i)**2))
        counter=counter+1
    return distance  

#function of Sort by distance and return indices of the first k neighbors
def sorting(dis,k):
    knearest=sorted(dis.items(), key=operator.itemgetter(1))
    knearest= knearest[:k]
    
    p={}
    a={0,1,2,3,4}
    for i in a:
        p[i]=knearest[i][0]
    print(p)
    return p

#Extract the labels of the k nearest neighbor training samples
def extract(k_idx):
    k_neighbour={}
    for i in k_idx:
        a=k_idx[i]
        k_neighbour[i]=y_train[a]
    print('K=5 NEAREST POINTS ARE:')    
    print(k_neighbour)
    return  k_neighbour
#find most common labels
def most_frequent(b):
    
    list=[b[0],b[1],b[2],b[3],b[4]]
    occurance_count=Counter(list)
    return occurance_count.most_common(1)[0][0]

In [2]:
dataset=pd.read_csv("C:\\Users\\DELL\\Desktop\iris.csv")
X=dataset.iloc[:,0:4].values
y=dataset.iloc[:,-1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [3]:
#normalising the data
D=dataset[['sepal_length','sepal_width','petal_length','petal_width']]
X=D.apply(lambda x: (x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0)))
X

sepal_length  sepal_width  petal_length  petal_width
0        0.222222     0.625000      0.067797     0.041667
1        0.166667     0.416667      0.067797     0.041667
2        0.111111     0.500000      0.050847     0.041667
3        0.083333     0.458333      0.084746     0.041667
4        0.194444     0.666667      0.067797     0.041667
..            ...          ...           ...          ...
145      0.666667     0.416667      0.711864     0.916667
146      0.555556     0.208333      0.677966     0.750000
147      0.611111     0.416667      0.711864     0.791667
148      0.527778     0.583333      0.745763     0.916667
149      0.444444     0.416667      0.694915     0.708333

[150 rows x 4 columns]

In [4]:
def knn(x1):
    k=5
    dis=ecu_distance(x1,X_train)
    k_idx=sorting(dis,k)
    b=extract(k_idx)
    common=most_frequent(b)
    print('the test data is belong to class:')
    return common
    
    
    

In [5]:
#1st test data 
x1=[5.1,2.5,3.2,4.3]
knn(x1)

{0: 5, 1: 90, 2: 81, 3: 32, 4: 20}
K=5 NEAREST POINTS ARE:
{0: 'setosa', 1: 'setosa', 2: 'virginica', 3: 'virginica', 4: 'setosa'}
the test data is belong to class:


'setosa'

In [6]:
#2nd test data
x2=[4.9,3,1.4,0.2]
knn(x2)

{0: 99, 1: 19, 2: 34, 3: 52, 4: 62}
K=5 NEAREST POINTS ARE:
{0: 'versicolor', 1: 'versicolor', 2: 'setosa', 3: 'setosa', 4: 'virginica'}
the test data is belong to class:


'versicolor'

In [7]:
#3rd test data
x3=[6,3,4.8,1.8]
knn(x3)

{0: 43, 1: 38, 2: 85, 3: 27, 4: 58}
K=5 NEAREST POINTS ARE:
{0: 'setosa', 1: 'virginica', 2: 'setosa', 3: 'versicolor', 4: 'setosa'}
the test data is belong to class:


'setosa'

In [9]:
#for accuracy and confusion matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)#encoding the dependent variables
le=LabelEncoder()
y=le.fit_transform(y)
classifier= KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',cm)
print('accuracy:')
accuracy_score(y_test,y_pred)

confusion matrix:
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
accuracy:


0.9666666666666667