In [1]:
#[1]print Hello World!

In [2]:
print("'Hello World!'")

'Hello World!'


In [3]:
# 2 algebraic operation

In [4]:
a = int(input('enter the 1st no:'))
b = int(input('enter the 2nd no:'))

enter the 1st no:5
enter the 2nd no:5


In [5]:
c=a+b
d=a-b
e=a*b
f=a/b
g=a%b

In [6]:
print(c,d,e,f,g)

10 0 25 1.0 0


In [7]:
# 3factorial of a number

In [8]:
num = int(input('enter the no:'))
f=1
for i in range (1,num+1):
    f=f*i
print('the factorial is:',f)
 

enter the no:5
the factorial is: 120


In [9]:
# 4 print prime no in an interval

In [10]:
a=int(input('enter the lower interval:'))
b=int(input('enter the upper interval'))
print('prime numbers inthe interval',a,'and',b,'are')
for n in range(a,b+1):  #prime number is always greater than one
    if n>1:
        for i in range (2,n):
            if n%i==0:
                break
        else:
            print(n)

enter the lower interval:5
enter the upper interval5
prime numbers inthe interval 5 and 5 are
5


In [11]:
#5 Lcm of two number

In [12]:
a= int(input('enter the first number:'))
b= int(input('enter the second number:'))
for n in range (1,a*b+1):
    if n%a==0and n%b==0:
        print('LCM of two number is:',n)
        break

enter the first number:56
enter the second number:56
LCM of two number is: 56


In [13]:
my_list =[2,4,53,45,12,13,34,54,23,97,101,67,48,51,58]
pos = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
L=len(my_list)
for i in range (0,L):
    for j in range(0,L-i-1):
        if my_list[j]< my_list[j+1]:
            (my_list[j],my_list[j+1])=(my_list[j+1],my_list[j])
            (pos[j],pos[j+1])=(pos[j+1],pos[j])
            
print('the sorted element in descending order is:',my_list)
print('the indices of the soeted element are:',pos)

the sorted element in descending order is: [101, 97, 67, 58, 54, 53, 51, 48, 45, 34, 23, 13, 12, 4, 2]
the indices of the soeted element are: [11, 10, 12, 15, 8, 3, 14, 13, 4, 7, 9, 6, 5, 2, 1]


In [14]:
#7 sorting in ascending order using numpy

In [15]:
import numpy as np

In [16]:
m_list=np.array([2,4,3,1,5,34,23,31,13,33,42,24,56,65,78])
pos=np.arange(1,16)


In [17]:
L=len(m_list)
for i in range (0,L):
    for j in range (0,L-i-1):
        if m_list[j]>m_list[j+1]:
            (m_list[j],m_list[j+1])=(m_list[j+1],m_list[j])
            (pos[j],pos[j+1])=(pos[j+1],pos[j])
print('the sorted element in ascending order is:',m_list)
print('the indices of the sorted element are:',pos)

the sorted element in ascending order is: [ 1  2  3  4  5 13 23 24 31 33 34 42 56 65 78]
the indices of the sorted element are: [ 4  1  3  2  5  9  7 12  8 10  6 11 13 14 15]


In [18]:
# 8 print the matrix

In [19]:
import random

In [20]:
m = int(input('enter the row order'))
n = int(input("enter the column order"))
arr1= np.random.randint(-2.5,2.5,(m,n))
print(arr1)

enter the row order6
enter the column order6
[[ 0 -2  1  1  1 -1]
 [-2 -2  0  0  1 -2]
 [ 0  0 -2  0 -2 -1]
 [-1 -2  0  1 -1  1]
 [-1 -1  0  1 -1  0]
 [-2  0  0 -1 -2  0]]


In [21]:
#9 multiplication of matrix

In [22]:
import sys
from numpy import*

In [ ]:
m=int(input("first matrix rows:"))
n=int(input('first matrix columns:'))
m1 = []
for i in range (0,m):
    m1.append([])
for i in range (0,m):
    for j in range(0,n):
        m1[i].append(j)
        m1[i][j]=0
        print('entry in row ',i+1,'column:',j+1)
print(m1)
n1=int(input('second matrix rows:'))
p=int(input('second matrix columns:'))
m2=[]
for i in range (0,n1):
    m2.append([])
for i in range (0,n1):
    for j in range (0,p):
        m2[i].append(j)
        m2[i][j]=0
        print('entry in row:',i+1,'column:',j+1)
        m2[i][j]=int(input())
print(m2)
Res = []
for i in range (0,m):
    Res.append([])
for i in range (0,m):
    for j in range(0,p):
        Res[i].append(j)
        Res[i][j]=0
for n1 in range (len(m1)):
    for p in range (len(m2[0])):
        for q in range (len(m2)):
            Res[n1][p]+=m1[n1][q]*m2[q][p]
print(Res)

In [ ]:
# 13 plot the function y = 3x + 2

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
x = np.linspace(-10,10)
y = 3*x +2
plt.plot(x,y)
plt.title('plot of function y = 3x + 2')
plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.show()

In [ ]:
# define class for a complex no